import Foundation

// Your own ~/.ssh/config: lists its hosts for the Hosts menu, and exports a
// copy Blink can read into Blink's iCloud Drive folder.
//
// In Blink, two lines at the end of its ~/.ssh/config pick the export up.
// Blink resolves relative Includes against the including file's folder, and
// Blink's ~/iCloud links to its iCloud Drive folder. The `Host *` matters:
// Blink scopes an Include to the Host block it appears in.
//
//   Host *
//     Include ../iCloud/wink/ssh_config

enum LocalSSHConfig {
  static let home = FileManager.default.homeDirectoryForCurrentUser
  static let configURL = home.appendingPathComponent(".ssh/config")

  /// Blink's iCloud Drive "Documents" folder (Blink's ~/iCloud).
  static var blinkICloudDir: URL? {
    let base = home.appendingPathComponent("Library/Mobile Documents")
    return ["iCloud~sh~blink~blinkshell", "iCloud~com~carloscabanero~blinkshell"]
      .map { base.appendingPathComponent($0).appendingPathComponent("Documents") }
      .first { FileManager.default.fileExists(atPath: $0.path) }
  }
  static var blinkExportURL: URL? {
    blinkICloudDir?.appendingPathComponent("wink/ssh_config")
  }
  /// Run once in a Blink shell to include the export.
  static let blinkSetupCommands = [
    "echo 'Host *' >> ~/.ssh/config",
    "echo '  Include ../iCloud/wink/ssh_config' >> ~/.ssh/config",
  ]

  // MARK: - Reading

  /// ~/.ssh/config with Includes inlined. Wink's own generated files are
  /// skipped so Blink's hosts never loop back into the export.
  static func flattenedLines(_ url: URL = configURL, depth: Int = 0) -> [String] {
    guard depth < 8, let text = try? String(contentsOf: url, encoding: .utf8) else { return [] }
    var out: [String] = []
    var inBlock = false
    for line in text.components(separatedBy: .newlines) {
      let (key, value) = split(line)
      if key == "host" || key == "match" { inBlock = true }
      guard key == "include" else { out.append(line); continue }
      var included: [String] = []
      for pattern in value.split(separator: " ").map(String.init) {
        for path in glob(resolveInclude(pattern)) where !path.hasPrefix(BlinkConfig.winkDir.path) {
          included += flattenedLines(URL(fileURLWithPath: path), depth: depth + 1)
        }
      }
      out += included
      // An included file's last Host block must not swallow the global
      // options that follow the Include line here.
      if !inBlock, included.contains(where: { ["host", "match"].contains(split($0).0) }) {
        out.append("Host *")
      }
    }
    return out
  }

  /// Concrete host aliases (no wildcards or negations), in file order.
  static func hostAliases(from url: URL = configURL) -> [String] {
    var seen = Set<String>(), out: [String] = []
    for line in flattenedLines(url) {
      let (key, value) = split(line)
      guard key == "host" else { continue }
      for alias in value.split(separator: " ").map(String.init)
      where !alias.contains(where: { "*?!".contains($0) }) && seen.insert(alias).inserted {
        out.append(alias)
      }
    }
    return out
  }

  // MARK: - Export for Blink

  // Blink's parser (github.com/blinksh/SSHConfig) rejects the whole config on
  // `Match`, on non yes/no values for these keys, and on non-numbers for those.
  private static let yesNo: Set<String> = [
    "batchmode", "canonicalizefallbacklocal", "challengeresponseauthentication", "checkhostip",
    "clearallforwardings", "compression", "enablesshkeysign", "exitonforwardfailure", "forwardagent",
    "forwardx11", "forwardx11trusted", "gatewayports", "gssapiauthentication",
    "gssapidelegatecredentials", "hostbasedauthentication", "identitiesonly",
    "kbdinteractiveauthentication", "nohostauthenticationforlocalhost", "passwordauthentication",
    "permitlocalcommand", "pubkeyauthentication", "rhostsrsaauthentication", "rsaauthentication",
    "streamlocalbindunlink", "tcpkeepalive", "usekeychain", "useprivilegedport", "visualhostkey",
  ]
  private static let uints: Set<String> = [
    "canonicalizemaxdots", "compressionlevel", "connectionattempts", "connecttimeout",
    "numberofpasswordprompts", "port", "serveralivecountmax", "serveraliveinterval",
  ]
  // Options that point at Mac-local sockets/paths and mean nothing in Blink.
  private static let macOnly: Set<String> = [
    "identityagent", "controlpath", "controlpersist", "usekeychain", "addkeystoagent",
    "userknownhostsfile", "globalknownhostsfile", "certificatefile",
  ]

  struct Export {
    var text: String
    /// Blink key names the exported hosts use, mapped to the local private key file.
    var keys: [String: URL]
  }

  static func blinkExport(from url: URL = configURL) -> Export {
    var out = """
      # Generated by Wink from ~/.ssh/config on your Mac. Don't edit here;
      # it's rewritten whenever that file changes. IdentityFile entries are
      # Blink key names: import each key into Blink under that name.


      """
    var keys: [String: URL] = [:]
    var inMatch = false
    for line in flattenedLines(url) {
      let (key, value) = split(line)
      if key == "match" { inMatch = true; continue }
      if key == "host" { inMatch = false }
      if inMatch || macOnly.contains(key) { continue }
      if yesNo.contains(key) {
        let v = value.lowercased()
        guard v == "yes" || v == "no" else { continue }
        if v != value { out += "  \(line.trimmingCharacters(in: .whitespaces).prefix(key.count)) \(v)\n"; continue }
      }
      if uints.contains(key), UInt(value) == nil { continue }
      if key == "identityfile" {
        let path = expand(value.trimmingCharacters(in: CharacterSet(charactersIn: "\"")))
        var name = (path as NSString).lastPathComponent
        if name.hasSuffix(".pub") { name = String(name.dropLast(4)) }
        let priv = URL(fileURLWithPath: path.hasSuffix(".pub") ? String(path.dropLast(4)) : path)
        if isPrivateKey(priv) { keys[name] = priv }
        out += "  IdentityFile \(name)\n"
        continue
      }
      out += line + "\n"
    }
    return Export(text: out, keys: keys)
  }

  /// Rewrites the Blink copy if it changed. Returns the export either way.
  @discardableResult
  static func writeBlinkExport() throws -> Export {
    let export = blinkExport()
    guard let url = blinkExportURL else {
      throw NSError(domain: "Wink", code: 2, userInfo: [NSLocalizedDescriptionKey:
        "Blink's iCloud Drive folder wasn't found. Is iCloud Drive on, and has Blink been opened on this Mac?"])
    }
    if (try? String(contentsOf: url, encoding: .utf8)) != export.text {
      try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
      try export.text.write(to: url, atomically: true, encoding: .utf8)
    }
    return export
  }

  // MARK: - Keys

  static func isPrivateKey(_ url: URL) -> Bool {
    guard let h = try? FileHandle(forReadingFrom: url) else { return false }
    defer { try? h.close() }
    let head = String(decoding: h.readData(ofLength: 64), as: UTF8.self)
    return head.hasPrefix("-----BEGIN") && head.contains("PRIVATE KEY")
  }

  /// Private keys in ~/.ssh and ~/.config/wink/keys, by file name.
  static func localPrivateKeys() -> [String: URL] {
    var out: [String: URL] = [:]
    for dir in [home.appendingPathComponent(".ssh"), BlinkConfig.keysDir] {
      for url in (try? FileManager.default.contentsOfDirectory(at: dir, includingPropertiesForKeys: nil)) ?? []
      where isPrivateKey(url) {
        out[url.lastPathComponent] = url
      }
    }
    return out
  }

  // MARK: - helpers

  /// Lowercased keyword and its value; handles `Key value` and `Key=value`.
  static func split(_ line: String) -> (String, String) {
    let t = line.trimmingCharacters(in: .whitespaces)
    guard !t.isEmpty, !t.hasPrefix("#"),
          let r = t.rangeOfCharacter(from: CharacterSet(charactersIn: " \t=")) else {
      return (t.hasPrefix("#") ? "" : t.lowercased(), "")
    }
    let value = t[r.upperBound...].trimmingCharacters(in: CharacterSet(charactersIn: " \t="))
    return (t[..<r.lowerBound].lowercased(), value)
  }

  private static func expand(_ path: String) -> String {
    (path as NSString).expandingTildeInPath
  }

  /// OpenSSH resolves relative user Includes against ~/.ssh.
  private static func resolveInclude(_ pattern: String) -> String {
    let p = expand(pattern)
    return p.hasPrefix("/") ? p : home.appendingPathComponent(".ssh").appendingPathComponent(p).path
  }

  private static func glob(_ pattern: String) -> [String] {
    var g = glob_t()
    defer { globfree(&g) }
    guard Darwin.glob(pattern, 0, nil, &g) == 0 else { return [] }
    return (0..<Int(g.gl_pathc)).compactMap { g.gl_pathv[$0].map { String(cString: $0) } }
  }
}
